### ISSUE TITLE
output values are not recalculated when input value is changed

### ISSUE THREAD

**Issue by grzeartur** [katecpp/ElectricalCableCalculator#1]
In case of input value change new calculations won't be done, because Param is available from previous run:
if **(!isAvailable(param)** && isCalculationPossible(param))

**Comment by katecpp** [comment]
Solved by https://github.com/katecpp/ElectricalCableCalculator/commit/0ccf7dd12c7f06feb8715dbed69ae0163dc64617 .

Changed condition to isUserInput instead of isAvailable.
