### ISSUE TITLE
[GUI] Input cannot become an output

### ISSUE THREAD

**Issue by grzeartur** [katecpp/ElectricalCableCalculator#19]
When some field is used as input and then user removes value and wants to use it as output field it doesn't work. There remains "?" character instead of output value (engine returns valid output). 

![image](https://user-images.githubusercontent.com/20712433/27014149-e845c7e4-4ef2-11e7-9eca-9db7bb0287a6.png)
CableDiameter used as input

![image](https://user-images.githubusercontent.com/20712433/27014152-fc155578-4ef2-11e7-976b-d7d6b4570ea4.png)
CableDiameter should contain calculated output value

**Comment by katecpp** [comment]
Solved with https://github.com/katecpp/ElectricalCableCalculator/commit/64737f11521077ae0b96eeb9d21019c50b52b6b8
